### ISSUE TITLE
Fix scrollbar is in the middle of the "select-experience" page

### ISSUE THREAD

**Issue by harshcrop** [beckn/beckn-exp-guide-ui#209]
Description:

On the ["Select-Experience"](https://experience.becknprotocol.io/select-experience) page, the scrollbar appears in the middle of the page. This disrupts the internal scrolling behavior and affects the user experience.

Steps to Reproduce:

Go to the [Select-Experience page](https://experience.becknprotocol.io/select-experience).
Observe that the scrollbar appears in the middle of the page.
Expected Behavior: The scrollbar should appear on the right side of the page and have smooth and natural scrolling behavior.

Actual Behavior: The scrollbar is positioned in the middle of the page, causing awkward scrolling.

Solution: We need to fix the internal scroll behavior and ensure that the scrollbar is positioned correctly on the right side of the page.

**Comment by viraj89** [comment]
@omkar-em - can you please re-test this and request devs to fix it? 
cc @emmayank

**Comment by omkar-em** [comment]
Hi @harshcrop 
The scrollbar implementation aligns with an existing requirement. 
Please note that this was part of a previously agreed-upon design. 
Let me know if further clarification is needed.

Figma - 
https://www.figma.com/design/MRQi8ynptR0K14qZhpy2nf/Experience-Center?node-id=2798-1972&node-type=frame&t=6lTF8FEM5Ypf07WV-0

Let us know if any help needed.
cc: @viraj89 @emmayank
